language: android

dist: trusty
sudo: required 

android:
  components:
    - tools
    - platform-tools
    - android-26
    - build-tools-26.0.1

    
    
before_install:
- echo "y" | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- chmod +x gradlew
- apt-get -y install libxml2-utils

script:
- ./gradlew --stacktrace build connectedCheck
